# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch: # 手動觸發

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        check-latest: false

    - name: Clone external repository
      run: |  
        git clone https://github.com/Seraveegd/poe2-trade-app.git
        cd poe2-trade-app

    - name: Install dependencies
      run: |
        cd poe2-trade-app
        npm install

    - name: Build project
      run: |
        cd poe2-trade-app
        npm run electron

    - name: package
      run: |
        cd poe2-trade-app
        npm run package